# Generated by Django 3.1.13 on 2021-08-08 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pool_type', models.CharField(choices=[('SA', 'STANDALONE'), ('CM', 'COMMON'), ('GR', 'GROUP')], default='SA', max_length=2)),
                ('storage_type', models.CharField(choices=[('P', 'PERSISTENT'), ('E', 'EPHEMERAL')], default='E', max_length=1)),
                ('storage_capacity', models.IntegerField(default=256, verbose_name='Storage capacity in Mo of the pool, only if storage type is persistent.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=255))
            ],
        ),
    ]
