# Generated by Django 3.1.13 on 2021-08-08 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('version', models.CharField(default='', max_length=255)),
                ('cpu_capacity', models.FloatField(default=1.0, verbose_name='CPU capacity of the application.')),
                ('memory_capacity', models.IntegerField(default=256, verbose_name='Memory capacity of the application.')),
                ('application_file', models.FileField(upload_to='')),
                ('application_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.applicationpool')),
            ],
        ),
    ]
