# Generated by Django 3.1.13 on 2021-07-31 15:37

import PublicKey.validators.validate_public_key
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(choices=[('RSA', 'RSA')], max_length=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('value', models.TextField(validators=[PublicKey.validators.validate_public_key.validate_public_key], verbose_name='public key')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
